# -*- coding: utf-8 -*-
"""Метрика_для_оценки.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QBJ56ji0laVdfHEMe2ICO0IiU6BPvDd0
"""

import re
import math
import pandas as pd
from collections import Counter
from dataclasses import dataclass, field
from typing import List, Dict, Tuple, Optional
from comet import download_model, load_from_checkpoint

"""Что в нашем кейсе важнее всего?
Для успешного решения задачи нужно чтобы итоговый файл

1.   Запустился: не побитая разметка
2.   Отрендерился: не побитые теги
3.   Сохранил исходную информацию: не потерял теги и слова
4.   Был приемлемым для игры: имел достаточное кач-во перевода

Идея метрики такова: нужно посмотреть на качество перевода и качество сохранения тегов.
Для этого построим дерево тегов (чтобы оценить сохранение структуры) и посмотрим на общее сохранение тегов.
"""

# $VAR$, $VALUE|Y$, $NUM|2%$, ...
DOLLAR_VAR_RE = re.compile(r"\$[A-Za-z0-9_\|\.\+\-\%]+\$")
# £icon£
POUND_ICON_RE = re.compile(r"£[^£\s]+£")
# [Root.GetAdj], [This.GetName], [Root.Owner.GetSpecies.GetName], ...
SCRIPT_TAG_RE = re.compile(r"\[[^\]]+\]")
# §Y, §G, ...
COLOR_OPEN_RE = re.compile(r"§[A-Z]")
# §!
COLOR_CLOSE_RE = re.compile(r"§!")


def strip_tags_for_translation(text: str) -> str:
    """
    Удаление тегов перед оценкой качества перевода:
    - цветовые теги §X и §! убираются, но их содержимое остаётся;
    - плейсхолдеры/иконки/скрипты ($VAR$, £icon£, [Root.GetAdj]) выкидываются целиком.
    """
    t = DOLLAR_VAR_RE.sub(" ", text)
    t = POUND_ICON_RE.sub(" ", t)
    t = SCRIPT_TAG_RE.sub(" ", t)

    t = COLOR_OPEN_RE.sub("", t)
    t = COLOR_CLOSE_RE.sub("", t)

    t = re.sub(r"\s+", " ", t).strip()
    return t

@dataclass
class ColorSpan:
    start: int  # позиция по символам (начало маркера открытия)
    end: int    # позиция по символам (начало маркера закрытия)
    code: str   # буква цвета, например 'Y'


@dataclass
class TagToken:
    start: int
    end: int
    kind: str         # 'color_open', 'color_close', 'dollar', 'pound', 'script'
    payload: str = "" # код цвета / имя переменной / имя иконки / тело скрипта


@dataclass
class TagNode:
    kind: str
    value: Optional[str] = None
    children: List["TagNode"] = field(default_factory=list)


@dataclass
class TagSummary:
    root: TagNode

    n_color_spans: int
    n_color_open: int
    n_color_close: int
    n_dollar_vars: int
    n_pound_icons: int
    n_script_tags: int
    color_spans: List[ColorSpan]

    malformed_colors: bool
    malformed_placeholders: bool
    malformed_icons: bool
    malformed_scripts: bool

    @property
    def malformed_any(self) -> bool:
        """
        Есть ли какие-либо явные ошибки разметки,
        из-за которых файл может не запуститься.
        """
        return (
            self.malformed_colors
            or self.malformed_placeholders
            or self.malformed_icons
            or self.malformed_scripts
        )

"""Вкладывать можно только в теги цветов. Проверим и корректность всей структуры."""

def detect_illegal_nesting(text: str) -> Tuple[bool, bool, bool]:
    """
    Проверяет, есть ли внутри атомарных тегов ($...$, £...£, [....])
    какие-либо другие теги.
    Разрешённые вложения:
      - любые теги внутри цветового тега §X ... §!
    Запрещенные:
      - любой тег внутри $...$
      - любой тег внутри £...£
      - любой тег внутри [....]
    """
    tokens = extract_tag_tokens(text)

    malformed_placeholders = False
    malformed_icons = False
    malformed_scripts = False

    for i, outer in enumerate(tokens):
        if outer.kind not in ("dollar", "pound", "script"):
            continue

        for j, inner in enumerate(tokens):
            if i == j:
                continue

            if outer.start <= inner.start and inner.end <= outer.end:
                if outer.kind == "dollar":
                    malformed_placeholders = True
                elif outer.kind == "pound":
                    malformed_icons = True
                elif outer.kind == "script":
                    malformed_scripts = True

    return malformed_placeholders, malformed_icons, malformed_scripts

def summarize_tags(text: str) -> TagSummary:
    """
    Строит сводку по тегам в строке и проверяет побитость разметки.
    Здесь же строится дерево тегов
    """
    color_spans, malformed_colors_spans = find_color_spans(text)

    root, malformed_colors_tree = build_tag_tree(text)
    malformed_colors = malformed_colors_spans or malformed_colors_tree

    n_dollar = len(DOLLAR_VAR_RE.findall(text))
    n_pound  = len(POUND_ICON_RE.findall(text))
    n_script = len(SCRIPT_TAG_RE.findall(text))
    n_open   = len(COLOR_OPEN_RE.findall(text))
    n_close  = len(COLOR_CLOSE_RE.findall(text))

    # $ ... $ : каждая переменная даёт ровно два символа '$'
    n_dollar_chars = text.count("$")
    malformed_placeholders = (n_dollar_chars != 2 * n_dollar)

    # £icon£ : каждый маркер даёт два символа '£'
    n_pound_chars = text.count("£")
    malformed_icons = (n_pound_chars != 2 * n_pound)

    # [script] : каждый скрипт предполагает одну '[' и одну ']'
    n_lbrackets = text.count("[")
    n_rbrackets = text.count("]")
    malformed_scripts = (n_lbrackets != n_script) or (n_rbrackets != n_script)

    il_malformed_placeholders, il_malformed_icons, il_malformed_scripts = detect_illegal_nesting(text)

    malformed_placeholders = malformed_placeholders or il_malformed_placeholders
    malformed_icons        = malformed_icons        or il_malformed_icons
    malformed_scripts      = malformed_scripts      or il_malformed_scripts

    return TagSummary(
        root=root,
        n_color_spans=len(color_spans),
        n_color_open=n_open,
        n_color_close=n_close,
        n_dollar_vars=n_dollar,
        n_pound_icons=n_pound,
        n_script_tags=n_script,
        color_spans=color_spans,
        malformed_colors=malformed_colors,
        malformed_placeholders=malformed_placeholders,
        malformed_icons=malformed_icons,
        malformed_scripts=malformed_scripts,
    )


def find_color_spans(text: str) -> Tuple[List[ColorSpan], bool]:
    """
    Находит пары §X ... §! и возвращает список интервалов color spans.
    Если структура цветовых тегов нарушена — malformed=True.
    """
    events = []
    for m in COLOR_OPEN_RE.finditer(text):
        # ('open', position, 'Y')
        events.append(("open", m.start(), m.group()[1]))
    for m in COLOR_CLOSE_RE.finditer(text):
        # ('close', position, None)
        events.append(("close", m.start(), None))

    events.sort(key=lambda x: x[1])
    stack: List[Tuple[str, int]] = []
    spans: List[ColorSpan] = []
    malformed = False

    for kind, pos, code in events:
        if kind == "open":
            stack.append((code, pos))
        else:
            if not stack:
                malformed = True
                continue
            open_code, open_pos = stack.pop()
            span = ColorSpan(start=open_pos, end=pos, code=open_code)
            spans.append(span)

    if stack:
        # остались незакрытые открывающие
        malformed = True

    return spans, malformed


def extract_tag_tokens(text: str) -> List[TagToken]:
    """
    Извлекает все теги как плоский список токенов с позициями.
    """
    tokens: List[TagToken] = []

    for m in COLOR_OPEN_RE.finditer(text):
        tokens.append(TagToken(start=m.start(), end=m.end(),
                               kind="color_open", payload=m.group(0)[1]))
    for m in COLOR_CLOSE_RE.finditer(text):
        tokens.append(TagToken(start=m.start(), end=m.end(),
                               kind="color_close", payload=""))

    for m in DOLLAR_VAR_RE.finditer(text):

        payload = m.group(0)[1:-1]
        tokens.append(TagToken(start=m.start(), end=m.end(),
                               kind="dollar", payload=payload))

    for m in POUND_ICON_RE.finditer(text):

        payload = m.group(0)[1:-1]
        tokens.append(TagToken(start=m.start(), end=m.end(),
                               kind="pound", payload=payload))

    for m in SCRIPT_TAG_RE.finditer(text):

        payload = m.group(0)[1:-1]
        tokens.append(TagToken(start=m.start(), end=m.end(),
                               kind="script", payload=payload))

    tokens.sort(key=lambda t: t.start)
    return tokens


def build_tag_tree(text: str) -> Tuple[TagNode, bool]:
    """
    Строит дерево тегов:
    - color-узлы образуют иерархию по §X ... §!;
    - $VAR$, £icon£, [Root.Get...] становятся листьями у текущего color/корня.

    Возвращает (root, malformed_colors).
    malformed_colors = True, если структура цветовых тегов сломана
    (лишние закрывающие или незакрытые открывающие).
    """
    tokens = extract_tag_tokens(text)

    root = TagNode(kind="root")
    stack: List[TagNode] = [root]
    malformed = False

    for tok in tokens:
        parent = stack[-1]

        if tok.kind == "color_open":
            node = TagNode(kind="color", value=tok.payload)
            parent.children.append(node)
            stack.append(node)

        elif tok.kind == "color_close":
            # Закрываем последний открытый цвет
            if len(stack) == 1 or stack[-1].kind != "color":
                # Закрывающий цвет без открывающего или сломанный стек
                malformed = True
            else:
                stack.pop()

        elif tok.kind == "dollar":
            parent.children.append(TagNode(kind="dollar", value=tok.payload))

        elif tok.kind == "pound":
            parent.children.append(TagNode(kind="pound", value=tok.payload))

        elif tok.kind == "script":
            parent.children.append(TagNode(kind="script", value=tok.payload))

    # Если остались незакрытые цветовые теги
    if len(stack) > 1:
        malformed = True
        stack[:] = [root]

    return root, malformed

"""Блок оценивает корректность тегов в переводе и отвечает за три вещи:

1) **tag_type_recall** — считает полноту по каждому типу тегов.  
   Если в переводе отсутствуют теги, которые были в эталоне, это снижает recall.

2) **weighted_tag_content_score** — вычисляет итоговый скор сохранности тегов с разными весами:  цветовые теги важны меньше, иконки — больше, а переменные и скрипты — самые важные.  Итог — взвешенное среднее recall по типам тегов.

3) **tree_structure_score** — сравнивает структуру вложения тегов.  
   Строятся пути дерева от корня до каждого тега, и затем считается совпадение  
   путей между эталоном и кандидатом.

4) **compilability_score** — проверяет корректность разметки.  
   Если есть ошибки (незакрытые теги, запрещённые вложения), возвращает 0.

"""

def tag_type_recall(ref: TagSummary, cand: TagSummary) -> Dict[str, float]:
    """
    Recall по наличию тегов каждого типа.
    Штрафует за отсутствие тега в кандидате.
    """
    def safe_recall(gold: int, pred: int) -> float:
        if gold == 0:
            return 1.0
        return max(0.0, min(1.0, pred / gold))

    return {
        "color_spans":  safe_recall(ref.n_color_spans, cand.n_color_spans),
        "dollar_vars":  safe_recall(ref.n_dollar_vars, cand.n_dollar_vars),
        "pound_icons":  safe_recall(ref.n_pound_icons, cand.n_pound_icons),
        "script_tags":  safe_recall(ref.n_script_tags, cand.n_script_tags),
    }


def weighted_tag_content_score(ref: TagSummary, cand: TagSummary) -> float:
    """
    Оценивает сохранность тегов по типам, с разными весами:
    Выделение (цвет) < иконка < подстановка/скрипт.
    """
    recalls = tag_type_recall(ref, cand)

    weights = {
        "color_spans": 1.0,  # выделение
        "pound_icons": 2.0,  # иконки
        "dollar_vars": 3.0,  # подстановки
        "script_tags": 3.0,  # скрипты
    }

    num = 0.0
    den = 0.0
    for t, w in weights.items():
        num += w * recalls[t]
        den += w
    if den == 0:
        return 1.0
    return num / den


def collect_tag_paths(node: TagNode,
                      prefix: Tuple[str, ...],
                      paths: Counter) -> None:
    """
    Собирает пути вида ("color:Y", "dollar:STAR_NAME") для всех тегов.
    root сам по себе не учитываем как шаг пути.
    """
    if node.kind == "root":
        cur_prefix = prefix
    else:
        label = f"{node.kind}:{node.value}" if node.value is not None else node.kind
        cur_prefix = prefix + (label,)

    if not node.children:
        if cur_prefix:
            paths[cur_prefix] += 1
    else:
        for ch in node.children:
            collect_tag_paths(ch, cur_prefix, paths)


def tree_structure_score(ref_root: TagNode, cand_root: TagNode) -> float:
    """
    Сравниваем структуры деревьев тегов:
    строим мультисеты путей и считаем recall относительно рефа.
    """
    ref_paths: Counter = Counter()
    cand_paths: Counter = Counter()

    collect_tag_paths(ref_root, tuple(), ref_paths)
    collect_tag_paths(cand_root, tuple(), cand_paths)

    if not ref_paths:
        # В рефе тегов нет – структура не важна
        return 1.0

    intersect = 0
    total = sum(ref_paths.values())
    for p, cnt_ref in ref_paths.items():
        cnt_cand = cand_paths.get(p, 0)
        intersect += min(cnt_ref, cnt_cand)

    return max(0.0, min(1.0, intersect / total))


def tag_structure_score(ref: TagSummary, cand: TagSummary) -> float:
    """
    Структурное сходство дерева тегов:
    учитывает, какие теги вложены в какие цвета и в каком контексте находятся.
    """
    return tree_structure_score(ref.root, cand.root)


def compilability_score(tags: TagSummary) -> float:
    """
    1.0 если нет явных ошибок разметки (по типам тегов),
    0.0 если есть.
    """
    return 0.0 if tags.malformed_any else 1.0


def text_penalty(text_score: float, sharpness: float = 0.8, cutoff: float = 0.7) -> float:
    """
    Логарифмический штраф по качеству перевода, применяемый только
    до заданного порога cutoff. После cutoff штраф не используется.

    text_score ∈ [0,1]
    cutoff — порог, после которого penalty = 1.0
    """

    # защита от выхода за пределы
    t = max(0.0, min(1.0, text_score))

    # если перевели достаточно хорошо — штраф не применяется
    if t >= cutoff:
        return t

    # иначе логарифмический штраф
    s = max(1e-6, min(0.999999, sharpness))
    penalty = -math.log(1.0 - s * t) / -math.log(1.0 - s)

    return penalty

"""Для оценки качества перевода используется обучаемая нейронная метрика COMET (Crosslingual Optimized Metric for Evaluation of Translation). У COMET, неплохая корреляция с человеческими оценками.

В работе применяется библиотека unbabel-comet, поддерживаемая исследовательской группой Unbabel и доступная на GitHub и PyPI:
https://github.com/Unbabel/COMET

В качестве модели используется Unbabel/wmt22-comet-da. Она выдает скор в диапазоне от 0 до 1.


"""

#для чистого вывода
import os
import logging
logging.getLogger("pytorch_lightning").setLevel(logging.ERROR)
logging.getLogger("lightning").setLevel(logging.ERROR)
os.environ["COMET_DISABLE_PROGRESS_BAR"] = "1"

class CometScorer:
    """
    Ожидается модель 22 года или новее
    Возвращает скор в [0,1].
    """

    def __init__(self, comet_model):
        self.model = comet_model

    def score(self, src: Optional[str], ref: str, cand: str) -> float:
        """
        Семантический скор перевода в диапазоне [0,1].
        COMET использует исходное предложение, перевод и эталон.
        """
        src_text = strip_tags_for_translation(src) if src is not None else ""
        ref_text = strip_tags_for_translation(ref)
        cand_text = strip_tags_for_translation(cand)

        data = [{
            "src": src_text,
            "mt": cand_text,
            "ref": ref_text,
        }]

        out = self.model.predict(data, batch_size=8, gpus=0, progress_bar=False)

        score = float(out["scores"][0])


        return score

    def score_batch(
            self,
            src_list: List[Optional[str]],
            ref_list: List[str],
            cand_list: List[str],
            batch_size: int = 32,
    ) -> List[float]:
        """
        Батчевый расчёт COMET-скоров для списков src/ref/cand.
        Возвращает список float той же длины.
        """
        assert len(src_list) == len(ref_list) == len(cand_list)

        data = []
        for src, ref, cand in zip(src_list, ref_list, cand_list):
            src_text = strip_tags_for_translation(src) if src is not None else ""
            ref_text = strip_tags_for_translation(ref)
            cand_text = strip_tags_for_translation(cand)
            data.append({"src": src_text, "mt": cand_text, "ref": ref_text})

        out = self.model.predict(
            data,
            batch_size=batch_size,
            gpus=0,
            progress_bar=False,
        )

        return [float(s) for s in out["scores"]]

"""Функция **evaluate_translation** объединяет результаты всех подметрик и рассчитывает итоговый показатель качества перевода.
Оценка строится на четырёх компонентах:

1) Компилируемость (comp_score) — проверяет, нет ли ошибок во вложении тегов и может ли строка корректно загрузиться в игре.
   Если строка некорректна, итоговый балл принудительно обнуляется.

2) Сохранность тегов (tag_score) — комбинирует две подметрики:
*   tag_content_score — насколько полно в кандидате сохранены все типы тегов
*   tag_structure_score — насколько совпадает древовидная структура и вложенность тегов.
Сохранность тегов для нас важнее структуры.

3) Качество перевода (text_score) — семантическая метрика от XCOMET.
   На её основе вычисляется логарифмический штраф text_penalty(text_score), чтобы слабый перевод сильнее понижал итоговый балл.

4) Финальный результат — перемножение всех трёх факторов:
      `final = compilability * tag_score * text_penalty(text_score)`

"""

def evaluate_translation(
    ref: str,
    cand: str,
    src: Optional[str] = None,
    comet_scorer: Optional[CometScorer] = None,
    precomputed_text_score: Optional[float] = None,
) -> Dict[str, float]:
    """
    Главная функция.

    ref  — эталонный перевод.
    cand — перевод модели.
    src  — исходная строка (на языке источника), для COMET.
    comet_scorer — экземпляр CometScorer; если None — text_score=0.0.
    precomputed_text_score — уже посчитанный COMET-скор (если есть).
    """
    # Качество перевода
    if precomputed_text_score is not None:
        text_score = precomputed_text_score
    elif comet_scorer is not None:
        text_score = comet_scorer.score(src, ref, cand)
    else:
        text_score = 0.0

    # Теги
    ref_tags = summarize_tags(ref)
    cand_tags = summarize_tags(cand)

    tag_content = weighted_tag_content_score(ref_tags, cand_tags)
    tag_struct = tag_structure_score(ref_tags, cand_tags)

    # Контент тегов важнее структуры, но оба учитываем
    tag_score = 0.6 * tag_content + 0.4 * tag_struct

    # Компилируемость (запустится / не запустится)
    comp_score = compilability_score(cand_tags)

    # Финальный скор
    final = comp_score * tag_score * text_penalty(text_score)

    return {
        "text_score": text_score,
        "tag_content_score": tag_content,
        "tag_structure_score": tag_struct,
        "tag_score": tag_score,
        "compilability": comp_score,
        "final_score": final,
    }

if __name__ == "__main__":
    model_path = download_model("Unbabel/wmt22-comet-da")
    comet_model = load_from_checkpoint(model_path)
    scorer = CometScorer(comet_model)

    ref = 'Мы открыли §Y$STAR_NAME$§! в системе £star£ — [Root.GetAdj] звезда.'
    good = 'Мы обнаружили §Y$STAR_NAME$§! в системе £star£ — [Root.GetAdj] звезда.'
    missing_var = 'Мы обнаружили §Yзвезду§! в системе £star£ — [Root.GetAdj] $STAR_NAME$.'
    broken_color = 'Мы обнаружили §Y$STAR_NAME$ в системе £star£ — [Root.GetAdj] звезда.'  # нет §!

    src = "We have discovered a new star called $STAR_NAME$ in the system."

    results = {
    "good": evaluate_translation(ref, good, src=src, comet_scorer=scorer),
    "missing_var": evaluate_translation(ref, missing_var, src=src, comet_scorer=scorer),
    "broken_color": evaluate_translation(ref, broken_color, src=src, comet_scorer=scorer),
    }

    df = pd.DataFrame(results).T
    df = df[["text_score",
         "tag_content_score",
         "tag_structure_score",
         "tag_score",
         "compilability",
         "final_score"]]

# display(df.round(3))