from translator_app.storage.db import DatabaseService
from translator_app.storage.repositories import (
    JobRepository,
    SettingsRepository,
    ParsedFileRepository,
    TranslationUnitRepository,
    AttemptRepository,
    DiagnosticsRepository,
    RunHistoryRepository,
    CacheRepository,
)
from translator_app.storage.protection_snapshot_repository import (
    ProtectionSnapshotRepository,
)
from translator_app.storage.migrations import MigrationManager
from translator_app.storage.paths import (
    StoragePaths,
    get_storage_paths,
    get_config_path,
    get_secrets_path,
    get_profiles_path,
    get_prompt_presets_path,
    get_db_path,
    get_cache_path,
    get_trace_path,
    get_discovery_cache_path,
    get_raw_responses_dir,
    get_output_dir,
    clear_paths_cache,
    ENV_DATA_DIR,
    ENV_CONFIG_PATH,
    ENV_SECRETS_PATH,
    ENV_PROFILES_PATH,
    ENV_PROMPT_PRESETS_PATH,
    ENV_DB_PATH,
    ENV_CACHE_PATH,
    ENV_TRACE_PATH,
    ENV_DISCOVERY_CACHE_PATH,
    ENV_RAW_RESPONSES_DIR,
    ENV_OUTPUT_DIR,
)
from translator_app.storage.path_guard import (
    running_under_pytest,
    check_path_safe,
    get_pytest_tmp_dir,
    assert_all_env_vars_are_set,
)

__all__ = [
    "DatabaseService",
    "JobRepository",
    "SettingsRepository",
    "ParsedFileRepository",
    "TranslationUnitRepository",
    "AttemptRepository",
    "DiagnosticsRepository",
    "RunHistoryRepository",
    "CacheRepository",
    "ProtectionSnapshotRepository",
    "MigrationManager",
    # Centralized paths
    "StoragePaths",
    "get_storage_paths",
    "get_config_path",
    "get_secrets_path",
    "get_profiles_path",
    "get_prompt_presets_path",
    "get_db_path",
    "get_cache_path",
    "get_trace_path",
    "get_discovery_cache_path",
    "get_raw_responses_dir",
    "get_output_dir",
    "clear_paths_cache",
    # Env var names
    "ENV_DATA_DIR",
    "ENV_CONFIG_PATH",
    "ENV_SECRETS_PATH",
    "ENV_PROFILES_PATH",
    "ENV_PROMPT_PRESETS_PATH",
    "ENV_DB_PATH",
    "ENV_CACHE_PATH",
    "ENV_TRACE_PATH",
    "ENV_DISCOVERY_CACHE_PATH",
    "ENV_RAW_RESPONSES_DIR",
    "ENV_OUTPUT_DIR",
    # Path guard
    "running_under_pytest",
    "check_path_safe",
    "get_pytest_tmp_dir",
    "assert_all_env_vars_are_set",
]
